from common import *
def step(s, n):
    s.go(f"company?step={n}"); s.page.wait_for_selector("[data-step-panel] h2"); s.page.wait_for_timeout(400)
with sync_playwright() as p:
    s = S(p, "alex")
    step(s, 1)
    s.shot("35.1", "Company settings, step 1: Business details", callouts=[(".stepper", "Steps 1 to 8"), ("#legal_name", "Legal name"), ("#abn", "ABN"), ("label.btn.file", "Upload logo"), ("[data-form=business] button[type=submit]", "Save and continue")])
    step(s, 2)
    s.page.fill("#phone", "03 5700 0010")
    s.shot("35.2", "Step 2: Contact and addresses", callouts=[("#ba_street", "Business address"), ("#ba_state", "State"), ("[data-same]", "Postal address is the same"), ("#phone", "Phone"), ("#email", "Accounts email"), ("[data-form=contact] button[type=submit]", "Save and continue")])
    s.page.click("[data-form=contact] button[type=submit]"); s.page.wait_for_selector("[data-form=tax]"); s.page.wait_for_timeout(400)
    print("after save:", s.msg())
    s.shot("35.3", "Step 3: Tax and reporting (after saving step 2)", callouts=[("[data-msg]", "Saved."), ("#gst_registered", "Registered for GST"), ("#gst_basis", "GST reporting basis"), ("#bas_frequency", "BAS lodgement"), ("#financial_year_start_month", "Financial year starts"), ("#timezone", "Time zone")])
    step(s, 4)
    s.shot("35.4", "Step 4: Payroll and operations", callouts=[("fieldset.states", "States"), ("#pay_frequency", "Pay frequency"), ("#pay_day", "Pay day"), ("#super_clearing_house", "Super clearing house"), ("#pc_name", "Payroll contact"), ("[data-form=payroll] .note", "STP: export only")])
    step(s, 5)
    s.shot("35.5", "Step 5: Workers compensation", callouts=[("[data-wc] input[name=insurer]", "Insurer"), ("[data-wc] input[name=policy]", "Policy number"), ("[data-wc] input[name=expires]", "Expires"), ("[data-form=wc] button[type=submit]", "Save and continue")])
    step(s, 6)
    MASK = ["[data-step-panel] table.tbl tbody td:nth-child(2)", "[data-step-panel] table.tbl tbody td:nth-child(3)"]
    s.shot("35.6", "Step 6: Banking and payment terms (bank details masked)", callouts=[("#payment_terms_days", "Default payment terms"), ("[data-step-panel] table.tbl tbody .chip", "Status"), ("[data-retire]", "Retire"), ("#b_nickname", "Add a bank account"), ("form[data-form=bank] button[type=submit]", "Send for approval")], mask=MASK)
    s.page.fill("#b_nickname", "Demo payroll account"); s.page.fill("#b_account_name", "Panalo Pipes & Structurals Pty Ltd"); s.page.select_option("#b_purpose", "payroll")
    s.page.fill("#b_bsb", "12"); s.page.fill("#b_account_number", "11223344")
    s.page.click("form[data-form=bank] button[type=submit]"); s.page.wait_for_selector("[data-err=b_bsb]:has-text('BSB')")
    s.shot("35.7", "A field error: the BSB is too short", callouts=[("#b_bsb", "BSB field"), ("[data-err=b_bsb]", "Error message")], clip="form[data-form=bank]", mask=["#b_account_number"])
    s.page.fill("#b_bsb", "062-000"); s.page.click("form[data-form=bank] button[type=submit]")
    s.page.wait_for_selector("[data-msg]:has-text('Sent for approval')"); s.page.wait_for_timeout(400)
    s.shot("35.8", "A new bank account waiting for approval (bank details masked)", callouts=[("[data-step-panel] table.tbl tbody tr:first-child .chip", "Waiting for approval"), ("[data-msg]", "Sent for approval")], mask=MASK)
    step(s, 7)
    s.shot("35.9", "Step 7: Document numbering", callouts=[("tr[data-kind=project]", "Rows without labels"), ("tr[data-kind=invoice] input[name=prefix]", "Prefix"), ("tr[data-kind=invoice] input[name=next]", "Next number"), ("tr[data-kind=invoice] [data-preview]", "Next will be"), ("tr[data-kind=invoice] [data-save-number]", "Save (per row)")])
    step(s, 8)
    s.shot("35.10", "Step 8: Review", callouts=[("[data-step-panel] .msg", "Setup status"), ("[data-step-panel] table.kv", "Summary"), ("[data-finish]", "Finish setup / Saved")])
    s.close()
    s = S(p, "dana"); s.go("company"); s.page.wait_for_selector("table.kv"); s.page.wait_for_timeout(400)
    s.shot("35.11", "Company settings for someone without the Company settings permission (Dana Director)", callouts=[(".page-head .chip", "Read only"), ("table.kv", "Review summary only")])
    s.close()
