from common import *
with sync_playwright() as p:
    s = S(p, "dana"); s.go("dashboard"); s.page.wait_for_timeout(1500)
    s.shot("4.1", "The header bar", callouts=[(".brand", "Home (dashboard)"), ("[data-bell]", "Bell and unread count"), ("[data-who]", "Who is signed in"), ("a.top-link[href='../training/']", "Portal"), ("[data-signout]", "Sign out")], clip={"x": 0, "y": 0, "width": 1360, "height": 66})
    nav = s.page.locator("[data-nav]").bounding_box()
    s.shot("4.3", "Menu count badges (Dana Director)", callouts=[("a.nav-item[href='#/pay-runs'] .count", "Pay runs to approve"), ("a.nav-item[href='#/bas'] .count", "BAS to review"), ("a.nav-item[href='#/reconciliation'] .count", "Bank lines to match"), ("a.nav-item[href='#/payment-batches'] .count", "Batches to approve"), ("a.nav-item[href='#/approvals'] .count", "Approvals waiting")], clip={"x": 0, "y": 60, "width": 236, "height": nav["height"] + 20})
    s.page.click("[data-bell]"); s.page.wait_for_selector("[data-notes]:not(.hidden)")
    s.shot("4.4", "The notifications panel", callouts=[("[data-bell-count]", "Unread count"), ("[data-notes] li.unread a", "Notification (opens its screen)"), ("[data-read-all]", "Mark all read")], clip="viewport")
    print([x for x in s.page.locator("[data-notes] li").all_inner_texts()])
    s.close()
    s = S(p, "fran"); s.go("dashboard"); s.page.wait_for_timeout(1000)
    nav = s.page.locator("[data-nav]").bounding_box()
    s.shot("4.2", "The menu for a finance administrator (Fran Finance)", callouts=[(".nav-item.active", "Current screen"), (".nav-title:text-is('Sales')", "Menu group"), ("a.nav-item[href='#/bills']", "A menu item"), (".nav-title:text-is('Administration')", "Administration group")], clip={"x": 0, "y": 60, "width": 236, "height": nav["height"] + 20})
    s.go("invoices"); s.page.wait_for_selector("table.tbl tbody tr")
    s.shot("4.5", "A record list: Invoices", callouts=[(".tabs", "View tabs (filters)"), ("#i-q", "Search box"), ("form[data-filter] button", "Search"), ("table.tbl tbody tr td .chip", "Status chip"), ("table.tbl tbody tr td.mono a", "Open a record"), ("a.btn.primary", "New invoice")])
    s.go("bills/10bc5260-a7e0-4a9c-b799-f1ee3ca33997"); s.page.wait_for_selector(".actions")
    s.page.wait_for_timeout(500)
    print(s.page.locator(".actions").last.inner_text())
    s.shot("4.6", "A record with its action buttons and attachments (a bill for review)", callouts=[("h1 .chip", "Status"), (".actions a.btn:text-is('Edit')", "Edit (secondary)"), ("[data-approve]", "Approve (main action)"), (".actions .btn.danger", "Delete (destructive)"), ("[data-attachments] h2", "Attachments"), ("[data-attachments] label.btn.file", "Attach a PDF or photo")])
    s.close()
