const lessons = [
  {
    id:"scope", title:"1. Activity & Scope", critical:false,
    subtitle:"What the work is, who it applies to and the limits of online learning.",
    html:`<div class="learning-card"><h3>Activity</h3><p>This module covers MIG welding, tack welding, grinding and hot-metal handling in a workshop or client-site setting as assigned.</p></div>
    <div class="learning-card"><h3>Who this module is for</h3><p>Boilermakers, Welders and Trade Assistants as applicable. The approved role, licence, qualification and authorisation requirements must be verified before issue.</p></div>
    <div class="learning-card warning"><h3>Important</h3><p>Passing the online module does <strong>not</strong> replace hands-on competency verification where practical demonstration is required.</p></div>`,
    q:"After passing the online training, is a worker automatically authorised to perform the practical task?",
    options:["Yes, the online pass is enough.","No. Practical/onsite verification is still required where specified."], answer:1,
    remediation:"Review the training model: theory completion is not the same as practical authorisation."
  },
  {
    id:"hazards", title:"2. Main Hazards", critical:false,
    subtitle:"Recognise the main hazards before work starts.",
    html:`<div class="visual"><div><b>Arc radiation</b><span>Potential eye and skin injury.</span></div><div><b>Fumes</b><span>Airborne contaminants generated by welding.</span></div><div><b>Sparks & hot metal</b><span>Burn and fire hazards.</span></div></div>
    <div class="learning-card"><h3>Known hazards from the training input</h3><ul><li>Arc radiation and welding fumes</li><li>Sparks, hot metal and fire</li><li>Electric shock</li><li>Grinder kickback or disc failure</li><li>Gas-cylinder hazards</li></ul></div>
    <div class="learning-card good"><h3>Worker expectation</h3><p>Identify hazards before starting and again whenever the task, equipment, environment or conditions change.</p></div>`,
    q:"Which option is specifically identified as a hazard for this module?",
    options:["Arc radiation","Office lighting","Printer toner","Keyboard posture"], answer:0,
    remediation:"Review the listed task hazards before continuing."
  },
  {
    id:"controls", title:"3. Hierarchy of Controls", critical:true,
    subtitle:"Control the risk using higher-order controls before relying on PPE.",
    html:`<div class="learning-card"><h3>Control principle</h3><p>Use the hierarchy of controls. Do not rely on PPE where higher-level controls are reasonably practicable.</p></div>
    <div class="visual"><div><b>Engineering / physical controls</b><span>Examples may include suitable fume control, guarding and separation.</span></div><div><b>Administrative controls</b><span>Approved SWMS/JSA, procedures, exclusion areas and supervision.</span></div><div><b>PPE</b><span>Final protective layer, selected from the approved source.</span></div></div>
    <div class="learning-card warning"><h3>PPE status</h3><p>The exact required PPE has not been supplied in the input. <strong>VERIFY AGAINST CURRENT APPROVED PANALO PIPES / CLIENT / LEGAL REQUIREMENT BEFORE ISSUE.</strong></p></div>`,
    q:"What is the correct control approach when a higher-level control is reasonably practicable?",
    options:["Rely only on PPE.","Use the higher-level control and apply PPE as required by the approved source.","Ignore the hazard if the task is short.","Let each worker choose any control."], answer:1,
    remediation:"The training framework requires the hierarchy of controls, not PPE-only risk control."
  },
  {
    id:"documents", title:"4. SWMS / JSA & Procedures", critical:true,
    subtitle:"Use only the current approved documents for the task.",
    html:`<div class="learning-card"><h3>Before work</h3><p>Locate and use the current approved Panalo Pipes SWMS/JSA/hot-work procedure and any applicable client/site documents.</p></div>
    <div class="learning-card warning"><h3>Current document details not supplied</h3><p>Do not invent document numbers or client requirements. The approved references must be inserted before release.</p></div>
    <div class="learning-card"><h3>If conditions change</h3><p>Stop and reassess. The approved risk-control documents may need review or update before restart.</p></div>`,
    q:"What should you do if the work conditions change and the existing controls may no longer be adequate?",
    options:["Continue until the current weld is finished.","Stop, make safe, notify and reassess before restart.","Delete the SWMS.","Ask another worker to take over."], answer:1,
    remediation:"Changed conditions require stop-work and reassessment before authorised restart."
  },
  {
    id:"prestart", title:"5. PPE & Pre-start", critical:true,
    subtitle:"Inspect the person, area, tools and equipment before starting.",
    html:`<div class="learning-card"><h3>Critical pre-start items from the module input</h3><ul><li>Correct PPE from the approved source</li><li>Guards and discs suitable and in serviceable condition</li><li>Fume control available and correctly set up</li><li>Combustible hazards removed or controlled</li><li>Equipment condition checked</li><li>Gas cylinders secured</li><li>Exclusion area established where required</li></ul></div>
    <div class="learning-card warning"><h3>Defect rule</h3><p>Stop work for defects or changed conditions. Do not use equipment that fails the pre-start check.</p></div>`,
    q:"A grinding disc is damaged during the pre-start check. What should happen?",
    options:["Use it only for a short task.","Use it at lower speed.","Do not use it; stop, make safe and follow the defect/escalation process.","Ask another worker if it looks acceptable."], answer:2,
    remediation:"Damaged equipment is a stop-work condition in this training module."
  },
  {
    id:"sequence", title:"6. Safe Work Sequence", critical:false,
    subtitle:"Set up the task so hazards and quality controls are managed from the start.",
    html:`<div class="learning-card"><h3>Safe sequence</h3><ol><li>Confirm authorised task and current documents.</li><li>Inspect work area, equipment and controls.</li><li>Set up fume control, screens/exclusion controls and fire precautions as required by the approved procedure.</li><li>Confirm cylinder security and equipment condition.</li><li>Perform welding/grinding within the approved task controls.</li><li>Stop for defects, abnormal conditions or changes.</li><li>Shut down safely, manage hot material and complete required housekeeping/records.</li></ol></div>
    <div class="learning-card good"><h3>Key message</h3><p>Preparation is part of the job. Safe work does not begin at the trigger or welding arc.</p></div>`,
    q:"Which comes before starting the welding or grinding operation?",
    options:["Confirm documents, inspect the area/equipment and set up required controls.","Start immediately and inspect later.","Complete only the housekeeping.","Skip the pre-start if the job is familiar."], answer:0,
    remediation:"Safe work begins with task confirmation, pre-start checks and control setup."
  },
  {
    id:"stopwork", title:"7. STOP WORK", critical:true,
    subtitle:"Use the required response sequence when defects or changed conditions are found.",
    html:`<div class="visual"><div><b>STOP → MAKE SAFE</b><span>Cease the activity and control immediate danger.</span></div><div><b>NOTIFY → REASSESS</b><span>Escalate and review the changed condition.</span></div><div><b>UPDATE → AUTHORISE RESTART</b><span>Update documents if required and restart only when authorised.</span></div></div>
    <div class="learning-card warning"><h3>Required sequence</h3><p><strong>STOP → MAKE SAFE → NOTIFY → REASSESS → UPDATE DOCUMENTS IF REQUIRED → AUTHORISE RESTART.</strong></p></div>`,
    q:"Which sequence matches the required STOP WORK process?",
    options:["Stop → Restart → Notify","Stop → Make Safe → Notify → Reassess → Update Documents if Required → Authorise Restart","Notify → Continue → Reassess later","Make Safe → Restart immediately"], answer:1,
    remediation:"This is a critical checkpoint. Review the six-step STOP WORK sequence."
  },
  {
    id:"emergency", title:"8. Emergency & Incident Response", critical:false,
    subtitle:"Know when to stop, make safe, escalate and preserve evidence.",
    html:`<div class="learning-card"><h3>General response</h3><p>Stop the task, make the area safe if it is safe to do so, follow the current approved emergency/site arrangements, obtain assistance and report the event through the approved process.</p></div>
    <div class="learning-card warning"><h3>Site-specific details</h3><p>Emergency numbers, muster points, fire-response arrangements and client-specific rules were not supplied. Verify them before issue and site deployment.</p></div>`,
    q:"Which response best fits the training framework after an incident or emergency?",
    options:["Keep working unless a supervisor sees it.","Stop, make safe if safe to do so, follow approved emergency arrangements and report/escalate.","Leave without telling anyone.","Restart as soon as the equipment powers up."], answer:1,
    remediation:"Emergency and incident response requires stop, safe response, escalation and the approved reporting process."
  },
  {
    id:"ims", title:"9. Quality & IMS Controls", critical:false,
    subtitle:"Safety, quality, environment and controlled records work together.",
    html:`<div class="learning-card"><h3>Where applicable</h3><ul><li>Verify current WPS/WPQ requirements before welding.</li><li>Follow the applicable ITP and inspection requirements.</li><li>Maintain MTC/material and weld traceability where required.</li><li>Use suitable measuring equipment and controlled records.</li><li>Raise an NCR or other approved quality record when required.</li></ul></div>
    <div class="learning-card"><h3>Document control</h3><p>Only current approved documents should be employee-facing. Superseded versions must not be used for live work.</p></div>`,
    q:"Which is the correct IMS behaviour before welding where a WPS applies?",
    options:["Use any WPS with a similar material.","Verify and follow the current approved applicable WPS and associated requirements.","Use memory instead of documents.","Ignore traceability if production is urgent."], answer:1,
    remediation:"Quality controls depend on current approved documents and traceable records."
  }
];

const exam = [
 {q:"Online completion alone confirms practical authorisation.",o:["True","False"],a:1,c:false},
 {q:"Which hazard is part of this module?",o:["Arc radiation","Printer noise","Keyboard fatigue","Paper cuts"],a:0,c:false},
 {q:"Controls should follow the hierarchy of controls rather than relying only on PPE.",o:["True","False"],a:0,c:false},
 {q:"Current approved SWMS/JSA/procedures should be used for the task.",o:["True","False"],a:0,c:false},
 {q:"A damaged grinder disc may be used if the task is short.",o:["True","False"],a:1,c:true},
 {q:"Gas-cylinder security is identified as a critical control for this module.",o:["True","False"],a:0,c:false},
 {q:"If conditions change, the worker should continue until the task is complete.",o:["True","False"],a:1,c:true},
 {q:"Which STOP WORK sequence is correct?",o:["Stop → Restart → Notify","Stop → Make Safe → Notify → Reassess → Update Documents if Required → Authorise Restart","Notify → Continue → Review later"],a:1,c:true},
 {q:"Where applicable, current WPS/WPQ, ITP and traceability requirements form part of the task controls.",o:["True","False"],a:0,c:false},
 {q:"A learner who passes theory but has a required practical assessment outstanding should be shown as fully authorised.",o:["True","False"],a:1,c:true}
];

const KEY="pp-trn-wld-001-state-v1";
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{unlocked:0,passed:[],current:0,name:"",employeeId:"",final:null};
const hero=document.getElementById("hero"), lessonView=document.getElementById("lessonView"), finalView=document.getElementById("finalView");
const nameInput=document.getElementById("learnerName"), idInput=document.getElementById("employeeId");
nameInput.value=state.name||""; idInput.value=state.employeeId||"";

function save(){localStorage.setItem(KEY,JSON.stringify(state));updateProgress();renderNav();}
function renderNav(){
 const nav=document.getElementById("lessonNav"); nav.innerHTML="";
 lessons.forEach((l,i)=>{
   const b=document.createElement("button"); b.disabled=i>state.unlocked; b.className=state.current===i&&!lessonView.classList.contains("hidden")?"active":"";
   b.innerHTML=`<span>${i+1}.</span><span>${l.title.replace(/^\d+\. /,"")}</span><span class="nav-status">${state.passed.includes(i)?"✓":i>state.unlocked?"🔒":""}</span>`;
   b.onclick=()=>showLesson(i); nav.appendChild(b);
 });
 const final=document.createElement("button"); const unlocked=state.passed.length===lessons.length;
 final.disabled=!unlocked; final.className=!finalView.classList.contains("hidden")?"active":"";
 final.innerHTML=`<span>10.</span><span>Final Assessment</span><span class="nav-status">${state.final?.pass?"✓":!unlocked?"🔒":""}</span>`;
 final.onclick=showFinal; nav.appendChild(final);
}
function updateProgress(){
 const completed=state.passed.length+(state.final?.pass?1:0); const pct=Math.round((completed/(lessons.length+1))*100);
 document.getElementById("progressText").textContent=pct+"%"; document.getElementById("progressBar").style.width=pct+"%";
}
function showLesson(i){
 if(i>state.unlocked)return; state.current=i; hero.classList.add("hidden"); finalView.classList.add("hidden"); lessonView.classList.remove("hidden");
 const l=lessons[i]; const passed=state.passed.includes(i);
 lessonView.innerHTML=`<div class="lesson-head"><div><h2>${l.title}</h2><p class="sub">${l.subtitle}</p></div><span class="pill ${l.critical?"critical":""}">${l.critical?"CRITICAL CHECKPOINT":"CHECKPOINT"}</span></div>
 ${l.html}
 <div class="checkpoint"><h3>Knowledge checkpoint</h3><p class="question">${l.q}</p>
 <div id="opts">${l.options.map((x,n)=>`<label class="option"><input type="radio" name="cp" value="${n}" ${passed&&n===l.answer?"checked":""}> ${x}</label>`).join("")}</div>
 <button id="checkBtn" class="primary">${passed?"Checkpoint passed":"Check answer"}</button><div id="feedback"></div></div>
 <div class="actions"><button id="prevBtn" class="secondary" ${i===0?"disabled":""}>Previous topic</button><button id="nextBtn" class="primary" ${passed?"":"disabled"}>${i===lessons.length-1?"Go to final assessment":"Next topic"}</button></div>`;
 document.getElementById("checkBtn").onclick=()=>{
   const sel=lessonView.querySelector('input[name="cp"]:checked'); const fb=document.getElementById("feedback"); if(!sel){fb.innerHTML='<div class="feedback no">Choose an answer first.</div>';return}
   if(+sel.value===l.answer){
     fb.innerHTML='<div class="feedback ok">Correct. Checkpoint passed and the next topic is unlocked.</div>';
     if(!state.passed.includes(i))state.passed.push(i); state.unlocked=Math.max(state.unlocked,Math.min(i+1,lessons.length-1)); save(); document.getElementById("nextBtn").disabled=false;
   } else fb.innerHTML=`<div class="feedback no">Not yet. ${l.remediation}</div>`;
 };
 document.getElementById("prevBtn").onclick=()=>showLesson(Math.max(0,i-1));
 document.getElementById("nextBtn").onclick=()=>i===lessons.length-1?showFinal():showLesson(i+1);
 save(); window.scrollTo({top:0,behavior:"smooth"});
}
function showFinal(){
 if(state.passed.length!==lessons.length)return; hero.classList.add("hidden"); lessonView.classList.add("hidden"); finalView.classList.remove("hidden");
 finalView.innerHTML=`<div class="lesson-head"><div><h2>10. Final Knowledge Assessment</h2><p class="sub">6 standard + 4 critical questions. Recommended rule: 80% overall and 100% of critical questions correct.</p></div><span class="pill critical">FINAL</span></div>
 <div class="learning-card warning"><h3>Practical assessment remains required</h3><p>A theory pass does not confirm practical authorisation for this module.</p></div>
 <div class="exam-grid">${exam.map((x,i)=>`<div class="exam-q ${x.c?"critical":""}"><h4>Q${i+1}. ${x.q} ${x.c?'<span class="pill critical">CRITICAL</span>':""}</h4>${x.o.map((o,j)=>`<label class="option"><input type="radio" name="e${i}" value="${j}"> ${o}</label>`).join("")}</div>`).join("")}</div>
 <button id="gradeBtn" class="primary">Submit assessment</button><div id="examResult"></div>
 <div class="actions"><button id="backBtn" class="secondary">Back to Topic 9</button></div>`;
 document.getElementById("gradeBtn").onclick=gradeExam; document.getElementById("backBtn").onclick=()=>showLesson(lessons.length-1); renderNav(); window.scrollTo({top:0,behavior:"smooth"});
}
function gradeExam(){
 let correct=0,criticalOK=true,answered=0;
 exam.forEach((x,i)=>{const el=finalView.querySelector(`input[name="e${i}"]:checked`); if(el){answered++; if(+el.value===x.a)correct++; else if(x.c)criticalOK=false;} else if(x.c)criticalOK=false;});
 const score=Math.round((correct/exam.length)*100), pass=answered===exam.length&&score>=80&&criticalOK; state.final={score,criticalOK,pass,date:new Date().toISOString()}; save();
 document.getElementById("examResult").innerHTML=`<div class="result-card ${pass?"pass":"fail"}"><div class="status-big">${pass?"THEORY PASSED":"FURTHER TRAINING REQUIRED"}</div><p><strong>Score:</strong> ${score}% · <strong>Critical questions:</strong> ${criticalOK?"PASS":"NOT YET PASSED"}</p><p>${pass?"Next status: THEORY PASSED – PRACTICAL PENDING. Complete the required onsite assessor verification before any final authorisation.":"Review the relevant topics and retake the assessment. All critical questions must be correct."}</p></div>`;
}
document.getElementById("startBtn").onclick=()=>showLesson(Math.min(state.current,state.unlocked));
document.getElementById("saveLearner").onclick=()=>{state.name=nameInput.value.trim();state.employeeId=idInput.value.trim();save();alert("Learner details saved in this browser.");};
document.getElementById("resetCourse").onclick=()=>{if(confirm("Reset this pilot course on this browser?")){localStorage.removeItem(KEY);location.reload();}};
renderNav();updateProgress();