const slides=[
{id:1,title:"Title and scope",sub:"Hot Work: MIG Welding and Grinding Safety",visual:"../../assets/hazard-hotspot.svg",bullets:["Hybrid training module for boilermakers, welders and trade assistants.","Work activity: MIG welding, tack welding, grinding and hot metal handling.","Workshop / client site as assigned."],key:"This online module is the theory component. Practical verification is still required.",check:null},
{id:2,title:"Learning objectives",sub:"At the end of training, the employee should be able to...",visual:"../../assets/ppe-prestart.svg",bullets:["Identify MIG welding and grinding hazards.","Select and inspect PPE and equipment.","Apply hierarchy-of-control principles.","Follow SWMS/JSA, stop-work and emergency steps.","Recognise quality and traceability controls."],key:"Competency needs knowledge plus onsite verification.",check:null},
{id:3,title:"What the activity is and why it matters",sub:"MIG welding, tack welding, grinding and hot metal handling",visual:"../../assets/hot-work-setup.svg",bullets:["Creates or prepares welded fabricated components.","May be done in workshop or client site as assigned.","Only authorised/competent workers may perform the task.","Incorrect setup can cause fire, injury, defects or rework."],key:"Hot work must be controlled before sparks are created.",check:{q:"Which statement best matches this training?",o:["Hot work controls can be added after welding starts.","Hot work must be controlled before sparks are created.","Only grinding requires pre-start controls."],a:1,critical:false,why:"The reference PowerPoint states that hot work must be controlled before sparks are created."}},
{id:4,title:"Main hazards – hotspot review",sub:"Identify the hazards before work begins",visual:"../../assets/hazard-hotspot.svg",bullets:["Arc radiation.","Welding fumes.","Sparks and hot metal.","Electric shock.","Grinder kickback / disc failure.","Gas-cylinder hazards."],key:"Hazards must be identified before work and reconsidered when conditions change.",check:{q:"Which group contains only hazards identified for this module?",o:["Arc radiation, fumes, sparks, electric shock and grinder disc failure.","Office lighting, paper cuts and keyboard posture.","Traffic noise and printer toner only."],a:0,critical:false,why:"These hazards are listed in the module input and reference PowerPoint."}},
{id:5,title:"Hierarchy of controls applied",sub:"Do not jump straight to PPE",visual:"../../assets/fume-control.svg",bullets:["Eliminate or substitute where practical.","Use engineering controls: source capture, ventilation, guarding.","Use administrative controls: SWMS/JSA, permits, exclusion zones.","Use PPE as the final barrier, not the only control."],key:"Ventilation and source capture come before relying on respirators.",check:{q:"When a higher-order control is reasonably practicable, what should the worker do?",o:["Rely only on PPE.","Apply the higher-order control and use PPE as required.","Ignore the hazard for a short task."],a:1,critical:true,why:"The training prompt requires the hierarchy of controls and says not to rely on PPE when higher-level controls are reasonably practicable."}},
{id:6,title:"SWMS / procedure requirements",sub:"Plain worker-language expectations",visual:"../../assets/hot-work-setup.svg",bullets:["Read and follow the current approved SWMS/JSA.","Check job scope, site rules and required controls.","Use approved equipment, PPE and consumables only.","Pause and reassess if anything changes."],key:"If the work changes, controls must be reviewed before restart.",verify:"The exact Panalo Pipes SWMS/JSA/hot-work procedure and client/site rules must be inserted and verified before release.",check:{q:"The work location changes after the task starts. What should happen first?",o:["Continue using the old controls.","Pause, make safe and reassess the work and controls before restart.","Ask a co-worker to continue instead."],a:1,critical:true,why:"The PowerPoint states that if work changes, controls must be reviewed before restart."}},
{id:7,title:"PPE and pre-start checks",sub:"Inspect before energising tools",visual:"../../assets/ppe-prestart.svg",bullets:["Welding helmet/lens, eye/face, hearing, FR clothing, gloves and boots.","Respiratory PPE if required by controls and assessment.","MIG leads, plugs, torch, gas cylinder, regulator and hoses.","Grinder guard, correct disc, disc condition and switch function."],key:"A defect found before work is a prevented injury.",verify:"Required PPE must be confirmed from the current approved Panalo Pipes / client source before formal issue.",check:{q:"A damaged grinding disc is found during pre-start. What should the learner do?",o:["Use it for a short task.","Do not use it; stop, make safe and follow the defect / escalation process.","Reduce tool speed and continue."],a:1,critical:true,why:"The training input lists guards/discs and equipment condition as critical controls and requires stop-work for defects."}},
{id:8,title:"Correct vs unsafe practice",sub:"Grinders can cause severe injuries",visual:"../../assets/grinder-correct-unsafe.svg",bullets:["Guard fitted and equipment in serviceable condition.","Correct disc for the task and disc condition checked.","Workpiece controlled and safe tool handling used.","Sparks and exclusion area controlled.","Required PPE selected and inspected."],key:"Unsafe tool setup is a stop-work condition.",check:{q:"Which condition is unacceptable before using an angle grinder?",o:["Guard fitted and correct disc.","Damaged disc or missing guard.","Workpiece secured."],a:1,critical:true,why:"The module input identifies guards/discs and grinder disc failure as critical controls/hazards."}},
{id:9,title:"Safe work sequence",sub:"Follow a controlled sequence",visual:"../../assets/hot-work-setup.svg",bullets:["Confirm job scope, SWMS/JSA and authorisation.","Prepare work area, controls, screens and fire equipment.","Inspect PPE, welder, grinder, leads and cylinders.","Perform work within controls and monitor changing conditions.","Shutdown, cool/label hot metal, clean area and complete records."],key:"Sequence prevents missed controls.",check:{q:"Which action belongs at the start of the safe work sequence?",o:["Confirm job scope, documents and authorisation.","Complete records after the job only.","Start welding, then check controls."],a:0,critical:false,why:"The PowerPoint safe-work sequence begins with job scope, SWMS/JSA and authorisation."}},
{id:10,title:"Stop-work conditions",sub:"STOP → MAKE SAFE → NOTIFY → REASSESS → UPDATE → AUTHORISE",visual:"../../assets/stop-work.svg",bullets:["STOP the work.","MAKE SAFE without exposing yourself or others to further risk.","NOTIFY the supervisor / responsible person.","REASSESS the task and controls.","UPDATE DOCUMENTS IF REQUIRED.","AUTHORISE RESTART only when conditions are acceptable."],key:"A defect or changed condition means the task does not simply continue.",check:{q:"Which sequence matches the required stop-work response?",o:["Stop → Restart → Notify.","Stop → Make Safe → Notify → Reassess → Update Documents if Required → Authorise Restart.","Notify → Continue → Reassess later."],a:1,critical:true,why:"This is the stop-work sequence specified in the original training prompt."}},
{id:11,title:"Emergency and incident response",sub:"Respond early and report correctly",visual:"../../assets/hot-work-setup.svg",bullets:["Raise alarm and make the area safe if safe to do so.","Use extinguisher only if trained and safe.","Treat burns, eye injury, shock or fume symptoms as reportable.","Notify supervisor and complete incident/near-miss records."],key:"Small incidents can become major if not reported early.",verify:"Emergency numbers, site muster points and client-specific arrangements were not supplied and must be verified before deployment.",check:{q:"After an incident, which response matches the module?",o:["Continue unless production is stopped.","Raise alarm / make safe if safe, follow approved emergency arrangements and report.","Restart the task immediately after checking the tool."],a:1,critical:false,why:"The PowerPoint requires early response and correct reporting."}},
{id:12,title:"Quality / IMS controls",sub:"Safety and quality are connected",visual:"../../assets/traceability.svg",bullets:["Use current approved WPS/WPQ requirements where applicable.","Follow applicable ITP and inspection requirements.","Maintain MTC/material and weld traceability where required.","Use controlled measuring equipment and records.","Raise NCR / corrective action records when applicable."],key:"Current approved documents and traceable records support controlled fabrication.",verify:"Exact WPS/WPQR/WPQ, ITP, MTC and form references must be verified before issue.",check:{q:"Where a WPS applies, what should happen before welding?",o:["Use any similar WPS.","Verify and follow the current approved applicable WPS and associated requirements.","Rely on memory instead of the controlled document."],a:1,critical:false,why:"The training specification includes WPS/WPQ, ITP, MTC/material traceability and document control as relevant IMS requirements."}},
{id:13,title:"Scenario discussion",sub:"Apply the controls to changed conditions",visual:"../../assets/grinder-correct-unsafe.svg",bullets:["You find a cracked grinding disc during pre-start.","Sparks are landing near oily rags.","The extraction hood is unavailable.","A client asks you to change the work location."],key:"The correct answer starts with stop, make safe and reassess.",check:{q:"The extraction hood becomes unavailable before welding. What is the best response under this module?",o:["Start and rely only on PPE.","Stop / do not start, make safe, notify and reassess the controls before work proceeds.","Move closer to the fume source."],a:1,critical:true,why:"Loss of a required control is a changed condition. The module requires stop, make safe, notify and reassess."}},
{id:14,title:"Five things to remember",sub:"Worker memory anchors",visual:"../../assets/hazard-hotspot.svg",bullets:["Read the current SWMS/JSA before starting.","Control fumes, fire, sparks and hot metal at source.","Check grinder guard/disc and electrical leads every time.","Keep cylinders secured and the exclusion zone controlled.","Stop work if conditions are unsafe or unclear."],key:"No job is urgent enough to skip a critical control.",check:{q:"Which statement best summarises the module?",o:["Production urgency overrides minor controls.","No job is urgent enough to skip a critical control.","Experienced workers can skip pre-start checks."],a:1,critical:false,why:"This is the final worker-memory message from the reference PowerPoint."}}
];

const exam=[
{q:"Passing the online theory module alone gives practical authorisation.",o:["True","False"],a:1,c:false},
{q:"Which is a listed hazard in this module?",o:["Arc radiation","Office printer noise","Keyboard fatigue"],a:0,c:false},
{q:"The hierarchy of controls means PPE should not be the only control when higher-level controls are reasonably practicable.",o:["True","False"],a:0,c:false},
{q:"The current approved SWMS/JSA should be used for the task.",o:["True","False"],a:0,c:false},
{q:"A damaged grinding disc can be used if the task is short.",o:["True","False"],a:1,c:true},
{q:"Gas-cylinder security is identified as a critical control in the module input.",o:["True","False"],a:0,c:false},
{q:"If conditions change and controls may no longer be adequate, work should continue until the current task is finished.",o:["True","False"],a:1,c:true},
{q:"Which stop-work sequence is correct?",o:["Stop → Restart → Notify","Stop → Make Safe → Notify → Reassess → Update Documents if Required → Authorise Restart","Notify → Continue → Review later"],a:1,c:true},
{q:"Where applicable, WPS/WPQ, ITP and traceability are part of quality / IMS controls.",o:["True","False"],a:0,c:false},
{q:"If practical demonstration is required, a theory pass must still be followed by onsite practical verification before final authorisation.",o:["True","False"],a:0,c:true}
];

const KEY="panalo-pp-trn-wld-001-v2";
let st=JSON.parse(localStorage.getItem(KEY)||"null")||{unlocked:0,passed:[],current:0,final:null};
const landing=document.getElementById("landing"),lesson=document.getElementById("lesson"),assessment=document.getElementById("assessment");

function save(){localStorage.setItem(KEY,JSON.stringify(st));renderNav();updateProgress()}
function updateProgress(){const complete=st.passed.length+(st.final?.pass?1:0);const pct=Math.round(complete/(slides.length+1)*100);document.getElementById("pct").textContent=pct+"%";document.getElementById("bar").style.width=pct+"%"}
function renderNav(){
 const nav=document.getElementById("nav");nav.innerHTML="";
 slides.forEach((s,i)=>{const b=document.createElement("button");b.disabled=i>st.unlocked;b.className=!lesson.classList.contains("hidden")&&st.current===i?"active":"";b.innerHTML='<span class="navnum">'+s.id+'</span><span>'+s.title+'</span><span class="navstatus">'+(st.passed.includes(i)?"✓":i>st.unlocked?"🔒":"")+'</span>';b.onclick=()=>showSlide(i);nav.appendChild(b)});
 const b=document.createElement("button");const ready=st.passed.length===slides.length;b.disabled=!ready;b.className=!assessment.classList.contains("hidden")?"active":"";b.innerHTML='<span class="navnum">15</span><span>Final assessment</span><span class="navstatus">'+(st.final?.pass?"✓":!ready?"🔒":"")+'</span>';b.onclick=showAssessment;nav.appendChild(b)
}
function showSlide(i){
 if(i>st.unlocked)return;st.current=i;landing.classList.add("hidden");assessment.classList.add("hidden");lesson.classList.remove("hidden");
 const s=slides[i],done=st.passed.includes(i);
 const check=s.check?'<section class="checkpoint"><div class="slidepill '+(s.check.critical?"critical":"")+'">'+(s.check.critical?"CRITICAL CHECKPOINT":"KNOWLEDGE CHECK")+'</div><h3>Check your understanding</h3><p class="q">'+s.check.q+'</p>'+s.check.o.map((x,n)=>'<label class="option"><input type="radio" name="cp" value="'+n+'" '+(done&&n===s.check.a?"checked":"")+'> '+x+'</label>').join("")+'<button class="primary" id="check">Check answer</button><div id="feedback"></div></section>':'<section class="checkpoint"><div class="slidepill">LEARNING STEP</div><h3>Review complete?</h3><p class="q">Continue when you have read and understood this section.</p><button class="primary" id="complete">Mark complete & continue</button></section>';
 lesson.innerHTML='<div class="slidehead"><div><p class="eyebrow">POWERPOINT REFERENCE · SLIDE '+s.id+' OF 15</p><h1>'+s.title+'</h1><p>'+s.sub+'</p></div><span class="slidepill">'+(s.check?.critical?"CRITICAL AREA":"TRAINING")+'</span></div><div class="slidevisual"><img src="'+s.visual+'" alt=""></div><div class="contentcard"><h3>Key learning</h3><ul>'+s.bullets.map(x=>'<li>'+x+'</li>').join("")+'</ul></div><div class="contentcard keymsg"><h3>Key message</h3><p>'+s.key+'</p></div>'+(s.verify?'<div class="contentcard verify"><h3>Verification required before formal issue</h3><p>'+s.verify+'</p></div>':"")+check+'<div class="actions"><button class="secondary" id="prev" '+(i===0?"disabled":"")+'>Previous</button><button class="primary" id="next" '+(done||!s.check?"":"disabled")+'>'+(i===slides.length-1?"Final assessment":"Next")+'</button></div>';
 document.getElementById("prev").onclick=()=>showSlide(Math.max(0,i-1));document.getElementById("next").onclick=()=>i===slides.length-1?showAssessment():showSlide(i+1);
 if(s.check){document.getElementById("check").onclick=()=>{const pick=lesson.querySelector('input[name="cp"]:checked');const fb=document.getElementById("feedback");if(!pick){fb.innerHTML='<div class="feedback no">Select an answer before continuing.</div>';return}if(+pick.value===s.check.a){fb.innerHTML='<div class="feedback ok">Correct. '+s.check.why+' The next section is unlocked.</div>';passSlide(i);document.getElementById("next").disabled=false}else{fb.innerHTML='<div class="feedback no">Not yet. Review this section and try again.</div>'}}}
 else{document.getElementById("complete").onclick=()=>{passSlide(i);if(i===slides.length-1)showAssessment();else showSlide(i+1)}}
 save();window.scrollTo({top:0,behavior:"smooth"})
}
function passSlide(i){if(!st.passed.includes(i))st.passed.push(i);st.passed.sort((a,b)=>a-b);st.unlocked=Math.max(st.unlocked,Math.min(i+1,slides.length-1));save()}
function showAssessment(){
 if(st.passed.length!==slides.length)return;landing.classList.add("hidden");lesson.classList.add("hidden");assessment.classList.remove("hidden");
 assessment.innerHTML='<div class="slidehead"><div><p class="eyebrow">POWERPOINT REFERENCE · SLIDE 15 OF 15</p><h1>Final Knowledge Assessment</h1><p>Theory + practical verification</p></div><span class="slidepill critical">FINAL ASSESSMENT</span></div><div class="assessment-intro"><strong>Pass rule:</strong> 80% overall + 100% of critical questions. A theory pass does not provide practical authorisation. Onsite verification remains required.</div>'+exam.map((x,i)=>'<div class="examq '+(x.c?"critical":"")+'"><h3>Q'+(i+1)+'. '+x.q+(x.c?'<span class="badge">CRITICAL</span>':"")+'</h3>'+x.o.map((o,j)=>'<label class="option"><input type="radio" name="e'+i+'" value="'+j+'"> '+o+'</label>').join("")+'</div>').join("")+'<button class="primary large" id="submit">Submit final assessment</button><div id="result"></div><div class="actions"><button class="secondary" id="back14">Back to Slide 14</button></div>';
 document.getElementById("submit").onclick=grade;document.getElementById("back14").onclick=()=>showSlide(slides.length-1);renderNav();window.scrollTo({top:0,behavior:"smooth"})
}
function grade(){
 let correct=0,critical=true,answered=0;exam.forEach((x,i)=>{const p=assessment.querySelector('input[name="e'+i+'"]:checked');if(p){answered++;if(+p.value===x.a)correct++;else if(x.c)critical=false}else if(x.c)critical=false});
 const score=Math.round(correct/exam.length*100),pass=answered===exam.length&&score>=80&&critical;st.final={score,critical,pass,date:new Date().toISOString()};save();
 document.getElementById("result").innerHTML='<div class="result '+(pass?"pass":"fail")+'"><h2>'+(pass?"THEORY PASSED – PRACTICAL PENDING":"FURTHER TRAINING REQUIRED")+'</h2><p><strong>Score:</strong> '+score+'% &nbsp; | &nbsp; <strong>Critical questions:</strong> '+(critical?"PASS":"NOT YET PASSED")+'</p><p>'+(pass?"Complete the required onsite practical competency assessment before any final COMPETENT / AUTHORISED status is issued.":"Review the relevant lesson areas and retake the final assessment. All critical questions must be correct.")+'</p></div>'
}
document.getElementById("start").onclick=()=>showSlide(Math.min(st.current,st.unlocked));
document.getElementById("reset").onclick=()=>{if(confirm("Reset progress for this training module on this browser?")){localStorage.removeItem(KEY);location.reload()}};
renderNav();updateProgress();