-- Personnel files: each person's HR folder, sorted into categories.
--
-- * personnel_categories: the HR folder structure (01 Personal ... 11 Other).
-- * hr_document_types.personnel_category: where an accepted onboarding item
--   is filed.
-- * personnel_documents: every filed record. Onboarding uploads are filed
--   in place (same private storage path); typed answers are filed as a PDF
--   record generated by the admin API. HR can also add documents directly.
-- * Nothing is deleted: records are archived with a reason, so employment
--   records can be kept for the 7 years the Fair Work Regulations require.
begin;

create table public.personnel_categories (
  key text primary key check (key ~ '^[a-z][a-z0-9_]{1,39}$'),
  name text not null,
  description text not null default '',
  sensitive boolean not null default false,
  sort integer not null default 100
);

insert into public.personnel_categories (key, name, description, sensitive, sort) values
  ('personal', '01 Personal details & emergency contacts', 'Date of birth, address, phone and emergency contacts.', true, 10),
  ('identity', '02 Identity & right to work', 'Photo ID details, citizenship or visa and VEVO checks.', true, 20),
  ('tax', '03 Tax file number declaration', 'TFN declarations. Restricted under the Privacy (TFN) Rule 2015.', true, 30),
  ('super', '04 Superannuation', 'Choice of fund, stapled fund results and fund details.', true, 40),
  ('banking', '05 Bank & pay details', 'Bank account for pay.', true, 50),
  ('employment', '06 Contract & employment terms', 'Contracts, letters of offer, Fair Work and Casual Employment Information Statements.', false, 60),
  ('licences', '07 Licences, tickets & certificates', 'White Card, high-risk work licences, trade and training certificates.', false, 70),
  ('contractor', '08 ABN & insurance (contractors)', 'ABN details, public liability and workers compensation certificates.', false, 80),
  ('training', '09 Training & competency', 'Portal training certificates and practical verifications.', false, 90),
  ('performance', '10 Performance, conduct & separation', 'Reviews, warnings, resignation and termination records.', true, 100),
  ('other', '11 Other correspondence', 'Anything that does not fit above.', false, 110);

alter table public.hr_document_types
  add column personnel_category text references public.personnel_categories(key);

update public.hr_document_types as t set personnel_category = v.category
from (values
  ('personal_details', 'personal'), ('emergency_contact', 'personal'),
  ('right_to_work', 'identity'), ('photo_id', 'identity'),
  ('tfn_declaration', 'tax'), ('super_choice', 'super'), ('bank_details', 'banking'),
  ('contract', 'employment'), ('fwis_ack', 'employment'), ('casual_statement', 'employment'), ('contractor_agreement', 'employment'),
  ('certificates', 'licences'), ('white_card', 'licences'), ('tickets', 'licences'),
  ('abn_details', 'contractor'), ('public_liability', 'contractor'), ('workers_comp', 'contractor')
) as v(key, category)
where t.key = v.key;
update public.hr_document_types set personnel_category = 'other' where personnel_category is null;
alter table public.hr_document_types alter column personnel_category set not null;
alter table public.hr_document_types alter column personnel_category set default 'other';

create table public.personnel_documents (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees(id) on delete restrict,
  category text not null references public.personnel_categories(key),
  title text not null check (length(btrim(title)) between 2 and 160),
  path text not null unique,
  file_name text not null default '',
  source text not null check (source in ('onboarding_upload', 'onboarding_form', 'hr_upload')),
  source_item_id uuid references public.onboarding_items(id) on delete set null,
  source_file_id uuid unique references public.onboarding_files(id) on delete set null,
  expires_on date,
  filed_by uuid references public.training_profiles(id) on delete set null,
  filed_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references public.training_profiles(id) on delete set null,
  archive_reason text,
  check ((archived_at is null) = (archive_reason is null))
);
create index personnel_documents_employee_idx on public.personnel_documents (employee_id, category, filed_at desc);
create unique index personnel_documents_one_form_record on public.personnel_documents (source_item_id) where source = 'onboarding_form';

create or replace function public.personnel_file_document(
  p_actor uuid, p_employee uuid, p_category text, p_title text, p_path text, p_file_name text,
  p_source text, p_item uuid, p_file uuid, p_expires date)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_profile uuid;
begin
  perform public.app_require(p_actor, 'hr.manage');
  select profile_id into v_profile from public.employees where id = p_employee;
  if not found then
    raise exception 'Person not found on the register.' using errcode = 'P0002';
  end if;
  if not exists (select 1 from public.personnel_categories where key = p_category) then
    raise exception 'Unknown HR folder category.' using errcode = '22023';
  end if;
  if p_source = 'hr_upload' and (p_path is null or p_path !~ ('^personnel/' || p_employee::text || '/' || p_category || '/[A-Za-z0-9._-]{1,160}$')) then
    raise exception 'Invalid upload path.' using errcode = '22023';
  end if;
  if p_source = 'onboarding_form' and (p_path is null or p_path !~ ('^personnel/' || p_employee::text || '/' || p_category || '/[A-Za-z0-9._-]{1,160}$')) then
    raise exception 'Invalid record path.' using errcode = '22023';
  end if;
  if p_source in ('onboarding_upload', 'onboarding_form') then
    if p_item is null or not exists (
      select 1 from public.onboarding_items i join public.onboarding_requests r on r.id = i.request_id
      where i.id = p_item and i.status = 'accepted' and r.employee_id = p_employee) then
      raise exception 'Only accepted onboarding items are filed.' using errcode = '22023';
    end if;
  end if;
  if p_source = 'onboarding_upload' and not exists (
      select 1 from public.onboarding_files where id = p_file and item_id = p_item and path = p_path) then
    raise exception 'That file does not belong to the onboarding item.' using errcode = '22023';
  end if;

  -- Filing is idempotent: the same onboarding file or form is filed once.
  if p_source = 'onboarding_upload' then
    select id into v_id from public.personnel_documents where source_file_id = p_file;
  elsif p_source = 'onboarding_form' then
    select id into v_id from public.personnel_documents where source_item_id = p_item and source = 'onboarding_form';
  end if;
  if v_id is not null then
    return v_id;
  end if;

  insert into public.personnel_documents (employee_id, category, title, path, file_name, source, source_item_id, source_file_id, expires_on, filed_by)
  values (p_employee, p_category, left(btrim(p_title), 160), p_path, left(coalesce(p_file_name, ''), 200), p_source,
          p_item, case when p_source = 'onboarding_upload' then p_file end, p_expires, p_actor)
  returning id into v_id;
  perform public.ims_audit(p_actor, 'personnel_document_filed',
    jsonb_build_object('documentId', v_id, 'employeeId', p_employee, 'category', p_category, 'title', btrim(p_title), 'source', p_source), v_profile);
  return v_id;
end;
$$;

create or replace function public.personnel_archive_document(p_actor uuid, p_document uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_doc record;
begin
  perform public.app_require(p_actor, 'hr.manage');
  select d.*, e.profile_id into v_doc from public.personnel_documents d join public.employees e on e.id = d.employee_id
  where d.id = p_document for update of d;
  if not found then
    raise exception 'Document not found.' using errcode = 'P0002';
  end if;
  if v_doc.archived_at is not null then
    raise exception 'This document is already archived.' using errcode = '22023';
  end if;
  if length(btrim(coalesce(p_reason, ''))) < 3 then
    raise exception 'Give a reason for archiving, for the record.' using errcode = '22023';
  end if;
  update public.personnel_documents set archived_at = now(), archived_by = p_actor, archive_reason = btrim(p_reason) where id = p_document;
  perform public.ims_audit(p_actor, 'personnel_document_archived',
    jsonb_build_object('documentId', p_document, 'employeeId', v_doc.employee_id, 'category', v_doc.category, 'reason', btrim(p_reason)), v_doc.profile_id);
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array['personnel_categories', 'personnel_documents']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon, authenticated', t);
  end loop;
end;
$$;
grant select on table public.personnel_categories, public.personnel_documents to service_role;

do $$
declare
  f text;
begin
  foreach f in array array[
    'personnel_file_document(uuid, uuid, text, text, text, text, text, uuid, uuid, date)',
    'personnel_archive_document(uuid, uuid, text)']
  loop
    execute format('revoke execute on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end;
$$;

comment on table public.personnel_documents is 'Personnel (HR) files by category. Never deleted; archived with a reason. hr.manage only.';

commit;
